### ISSUE TITLE
Does this support fields that are added via methods?

### ISSUE THREAD

**Issue by daniyalzade** [douwevandermeij/admin-totals#6]
I want to aggregate the spend field for example, but spend is defined as a method on the admin interface, i.e. not a db field. It would be a nice addition!

**Comment by douwevandermeij** [comment]
Unfortunately it's not possible since the aggregation is done on DB level and admin methods are not accessible from SQL.
Checkout https://docs.djangoproject.com/en/2.2/topics/db/aggregation/ for more info.

**Comment by daniyalzade** [comment]
That's what i suspected. Thanks
