### ISSUE TITLE
Can not add model attribute

### ISSUE THREAD

**Issue by avoid-ashraful** [douwevandermeij/admin-totals#9]
![Screenshot 2020-03-13 at 11 49 17 PM](https://user-images.githubusercontent.com/35927647/76646541-59362d80-6585-11ea-9cab-14e862806319.png)
![Screenshot 2020-03-13 at 11 49 40 PM](https://user-images.githubusercontent.com/35927647/76646557-605d3b80-6585-11ea-9bb9-37c444c7ea8d.png)

is there any solution for that ?

**Comment by douwevandermeij** [comment]
Unfortunately only database fields are supported.
I'm not 100% sure, but you might solve this by implementing this function in SQL so the Django ORM will use that to calculate the balance.

**Comment by avoid-ashraful** [comment]
thank you so much, i have fixed it using Django ORM for all non database
fields.
